### ISSUE TITLE
Got an error multiple times.

### ISSUE THREAD

**Issue by Dheerajmadhukar** [BishopFox/h2csmuggler#10]
[ERROR] [Errno -5] No address associated with hostname: https://domain.tld/path
[ERROR] [Errno -5] No address associated with hostname: https://domain.tld/path
[ERROR] [Errno -5] No address associated with hostname: https://domain.tld/path
[ERROR] [Errno -5] No address associated with hostname: https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld/path
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain.tld

Command: python3 h2csmuggler.py --scan-list h2c_urls.txt --test --threads 800 2>/dev/null

When i manually visit the URLs/Domains/Paths, i can access them with 200/301/302 res code. Help me out please.

**Comment by rahultalekar** [comment]
[ERROR] [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123): https://domain

same error

**Comment by barra51** [comment]
Same error here.

**Comment by rahultalekar** [comment]
@Dheerajmadhukar do you find any solution for this issue ?

**Comment by hktalent** [comment]
me too
```
/h2csmuggler/./h2csmuggler.py", line 52, in establish_tcp_connection
    retSock.connect(connect_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1333, in _real_connect
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)
```

**Comment by hktalent** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/18223385/131434519-7ee6577a-fb3b-4100-8206-4ac10571f14b.png">

```
        ctx=ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
        ctx.set_ciphers('ALL')
        retSock = ctx.wrap_socket(sock, server_hostname=connect_args[0])
```
now fixed
@rahultalekar  @Dheerajmadhukar @the-bumble @riramar

**Comment by Dheerajmadhukar** [comment]
Thanks mate :)

**Comment by rahultalekar** [comment]
thanks @hktalent
