### ISSUE TITLE
Thread Issue

### ISSUE THREAD

**Issue by desmondlisiwei** [BishopFox/h2csmuggler#2]
Program hangs after the number of threads used with the tool for example specifying --threads 10, only 10 url request will be sent and program hangs after.

python3 h2csmuggler.py --scan-list ../xxx.txt --threads 10

[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
[INFO] Failed to upgrade.
.....

**Comment by the-bumble** [comment]
Hey! I saw you closed this issue. I was able to reproduce this issue and it's fixed with the latest commit. Hope that helps! Thank you :)
