### ISSUE TITLE
[ERROR] str, bytes or bytearray expected

### ISSUE THREAD

**Issue by RandomRobbieBF** [BishopFox/h2csmuggler#3]
Command
----

`python3 h2csmuggler.py --scan-list ../xxx.txt --threads 10`

List has urls set like `https://google.com`

Response
----
```
[ERROR] str, bytes or bytearray expected, not NoneType: https://://www.something.com
```

**Comment by the-bumble** [comment]
Resolved offline. This is the expected error for invalid URLs. Fixed unrelated parsing issues, though! Thanks for the submission!
