### ISSUE TITLE
exec App error 

### ISSUE THREAD

**Issue by idlefire** [BishopFox/h2csmuggler#7]
- % of customers impacted: [100]%
- Affected Users: [Engineers / Operators / Customers]
- Is revenue impacted: [Yes / No]
- Urgency: [High / Medium / Low]
- Deadline: [Date]

## What should the expected behavior be
How can I get it?
## Platform Affected
[ ] Dev
[ ] Preview
[ ] Production

## Steps to Reproduce
Steps to reproduce the behavior

### Additional context
OS, Desktop/Mobile, Browser, Date/Time, 
Kali 2020.02

### Relevant screenshots
![image](https://user-images.githubusercontent.com/18007341/94243752-6d9eae00-ff4a-11ea-8635-c458aa3e1f94.png)

**Comment by the-bumble** [comment]
Hi idlefire,

I believe you have a permissions issue with the user running docker-compose. See https://github.com/docker/compose/issues/4039.

Thank you,

Jake
